# Message definition used in tests
# basic ros types
bool bool_msg
int8 int8_msg
uint8 uint8_msg
int16 int16_msg
uint16 uint16_msg
int32 int32_msg
uint32 uint32_msg
int64 int64_msg
uint64 uint64_msg
float32 float32_msg
float64 float64_msg
string string_msg
time time_msg
duration duration_msg
# array
uint8[] byte_array_msg
float32[] float_array_msg
# Use messages from other packages
std_msgs/String std_string_msg
geometry_msgs/Pose[] pose_msg
